openapi: 3.0.1
info:
  title: Meme Generation
  description: A plugin that allows the user to generate memes using ChatGPT.
  version: 'v1'
servers:
  - url: https://memepluginchatgpt.azurewebsites.net/
paths:
  /generate_meme:
    post:
      operationId: generateMeme
      summary: Generate meme
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                memeTemplateName:
                  type: string
                  description: The name of the meme template. Leave empty if unclear, but try to guess if possible.
                memeText:
                  type: string
                  description: The text of the meme. If user did not specify exactly, creatively make your own based on user wishes. 2 Lines by default separated by single newline (unless you know the template requires more such as Expanding brain-4 lines, American Chopper Argument-6 lines).
                  required: true
              additionalProperties: false
      responses:
        "200":
          description: OK
          content:
            application/json:
              schema:
                type: object
                properties:
                  meme_link:
                    type: string
                    description: The link to the generated meme.
        "400":
          description: Bad Request
          content:
            application/json:
              schema:
                type: object
                properties:
                  error:
                    type: string
                    description: Error message indicating the reason for the failure.
        "500":
          description: Internal Server Error
          content:
            application/json:
              schema:
                type: object
                properties:
                  error:
                    type: string
                    description: Error message indicating an unexpected error.
